server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic: products
    topic2: updatedProducts
    topic3: deletedProducts
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
